// LCM type definitions
// This file automatically generated by lcm-dart.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:raccoon_transport/raccoon_transport.dart';

class AckT implements LcmMessage {
  static const int LCM_FINGERPRINT = 0x586a802a7c4f9485;

  int timestamp;
  String publisher_id;
  int seq_num;
  String subscriber_id;

  AckT({
    required this.timestamp,
    required this.publisher_id,
    required this.seq_num,
    required this.subscriber_id,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    encodeBody(buf);
  }

  @override
  void encodeBody(LcmBuffer buf) {
    buf.putInt64(timestamp);
    {
      final bytes = utf8.encode(publisher_id);
      buf.putUint32(bytes.length + 1);
      buf.putUint8List(bytes);
      buf.putUint8(0);
    }
    buf.putInt64(seq_num);
    {
      final bytes = utf8.encode(subscriber_id);
      buf.putUint32(bytes.length + 1);
      buf.putUint8List(bytes);
      buf.putUint8(0);
    }
  }

  static AckT decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint: expected 0x${BigInt.from(LCM_FINGERPRINT).toUnsigned(64).toRadixString(16).padLeft(16, '0')}, received 0x${BigInt.from(fingerprint).toUnsigned(64).toRadixString(16).padLeft(16, '0')}');
    }
    return decodeBody(buf);
  }

  static AckT decodeBody(LcmBuffer buf) {
    final timestamp = buf.getInt64();
    final publisher_id = () {
      final len = buf.getUint32();
      final bytes = buf.getUint8List(len - 1);
      buf.getUint8(); // null terminator
      return utf8.decode(bytes);
    }();
    final seq_num = buf.getInt64();
    final subscriber_id = () {
      final len = buf.getUint32();
      final bytes = buf.getUint8List(len - 1);
      buf.getUint8(); // null terminator
      return utf8.decode(bytes);
    }();

    return AckT(
      timestamp: timestamp,
      publisher_id: publisher_id,
      seq_num: seq_num,
      subscriber_id: subscriber_id,
    );
  }
}
