// LCM type definitions
// This file automatically generated by lcm-dart.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:raccoon_transport/raccoon_transport.dart';

class RetainRequestT implements LcmMessage {
  static const int LCM_FINGERPRINT = 0x9d2c8160caa65cbe;

  int timestamp;
  String channel;
  String subscriber_id;

  RetainRequestT({
    required this.timestamp,
    required this.channel,
    required this.subscriber_id,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    encodeBody(buf);
  }

  @override
  void encodeBody(LcmBuffer buf) {
    buf.putInt64(timestamp);
    {
      final bytes = utf8.encode(channel);
      buf.putUint32(bytes.length + 1);
      buf.putUint8List(bytes);
      buf.putUint8(0);
    }
    {
      final bytes = utf8.encode(subscriber_id);
      buf.putUint32(bytes.length + 1);
      buf.putUint8List(bytes);
      buf.putUint8(0);
    }
  }

  static RetainRequestT decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint: expected 0x${BigInt.from(LCM_FINGERPRINT).toUnsigned(64).toRadixString(16).padLeft(16, '0')}, received 0x${BigInt.from(fingerprint).toUnsigned(64).toRadixString(16).padLeft(16, '0')}');
    }
    return decodeBody(buf);
  }

  static RetainRequestT decodeBody(LcmBuffer buf) {
    final timestamp = buf.getInt64();
    final channel = () {
      final len = buf.getUint32();
      final bytes = buf.getUint8List(len - 1);
      buf.getUint8(); // null terminator
      return utf8.decode(bytes);
    }();
    final subscriber_id = () {
      final len = buf.getUint32();
      final bytes = buf.getUint8List(len - 1);
      buf.getUint8(); // null terminator
      return utf8.decode(bytes);
    }();

    return RetainRequestT(
      timestamp: timestamp,
      channel: channel,
      subscriber_id: subscriber_id,
    );
  }
}
