"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class scalar_i8_t(object):

    __slots__ = ["timestamp", "dir"]

    __typenames__ = ["int64_t", "int8_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.dir = 0
        """ LCM Type: int8_t """

    def encode(self):
        buf = BytesIO()
        buf.write(scalar_i8_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.timestamp, self.dir))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != scalar_i8_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return scalar_i8_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = scalar_i8_t()
        self.timestamp, self.dir = struct.unpack(">qb", buf.read(9))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if scalar_i8_t in parents: return 0
        tmphash = (0x5727e921d0e057b2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if scalar_i8_t._packed_fingerprint is None:
            scalar_i8_t._packed_fingerprint = struct.pack(">Q", scalar_i8_t._get_hash_recursive([]))
        return scalar_i8_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", scalar_i8_t._get_packed_fingerprint())[0]

