"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class screen_render_t(object):

    __slots__ = ["timestamp", "screen_name", "entries"]

    __typenames__ = ["int64_t", "string", "string"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.screen_name = ""
        """ LCM Type: string """
        self.entries = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(screen_render_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __screen_name_encoded = self.screen_name.encode('utf-8')
        buf.write(struct.pack('>I', len(__screen_name_encoded)+1))
        buf.write(__screen_name_encoded)
        buf.write(b"\0")
        __entries_encoded = self.entries.encode('utf-8')
        buf.write(struct.pack('>I', len(__entries_encoded)+1))
        buf.write(__entries_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != screen_render_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return screen_render_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = screen_render_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __screen_name_len = struct.unpack('>I', buf.read(4))[0]
        self.screen_name = buf.read(__screen_name_len)[:-1].decode('utf-8', 'replace')
        __entries_len = struct.unpack('>I', buf.read(4))[0]
        self.entries = buf.read(__entries_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if screen_render_t in parents: return 0
        tmphash = (0x4054b15297f126e1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if screen_render_t._packed_fingerprint is None:
            screen_render_t._packed_fingerprint = struct.pack(">Q", screen_render_t._get_hash_recursive([]))
        return screen_render_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", screen_render_t._get_packed_fingerprint())[0]

