"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from . import yolo_box_t as _yolo_box_t_mod

class yolo_frame_t(object):

    __slots__ = ["timestamp", "frame_width", "frame_height", "frame_size", "frame_data", "num_boxes", "boxes"]

    __typenames__ = ["int64_t", "int32_t", "int32_t", "int32_t", "byte", "int32_t", "exlcm.yolo_box_t"]

    __dimensions__ = [None, None, None, None, ["frame_size"], None, ["num_boxes"]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.frame_width = 0
        """ LCM Type: int32_t """
        self.frame_height = 0
        """
        width of the frame
        LCM Type: int32_t
        """

        self.frame_size = 0
        """
        height of the frame
        LCM Type: int32_t
        """

        self.frame_data = b""
        """
        size of the frame data in bytes
        LCM Type: byte[frame_size]
        """

        self.num_boxes = 0
        """
        raw image data
        LCM Type: int32_t
        """

        self.boxes = []
        """
        number of detected boxes
        LCM Type: exlcm.yolo_box_t[num_boxes]
        """


    def encode(self):
        buf = BytesIO()
        buf.write(yolo_frame_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiii", self.timestamp, self.frame_width, self.frame_height, self.frame_size))
        buf.write(bytearray(self.frame_data[:self.frame_size]))
        buf.write(struct.pack(">i", self.num_boxes))
        for i0 in range(self.num_boxes):
            assert self.boxes[i0]._get_packed_fingerprint() == _yolo_box_t_mod.yolo_box_t._get_packed_fingerprint()
            self.boxes[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != yolo_frame_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return yolo_frame_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = yolo_frame_t()
        self.timestamp, self.frame_width, self.frame_height, self.frame_size = struct.unpack(">qiii", buf.read(20))
        self.frame_data = buf.read(self.frame_size)
        self.num_boxes = struct.unpack(">i", buf.read(4))[0]
        self.boxes = []
        for i0 in range(self.num_boxes):
            self.boxes.append(_yolo_box_t_mod.yolo_box_t._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if yolo_frame_t in parents: return 0
        newparents = parents + [yolo_frame_t]
        tmphash = (0xc38891426f6b4781+ _yolo_box_t_mod.yolo_box_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if yolo_frame_t._packed_fingerprint is None:
            yolo_frame_t._packed_fingerprint = struct.pack(">Q", yolo_frame_t._get_hash_recursive([]))
        return yolo_frame_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", yolo_frame_t._get_packed_fingerprint())[0]

