import '../parser/ast.dart';
import 'fingerprint.dart';
import 'type_mapper.dart';

/// Generates Dart code from LCM type definitions
class DartGenerator {
  final FingerprintCalculator _fingerprinter = FingerprintCalculator();
  final TypeMapper _typeMapper = TypeMapper();
  final StringBuffer _buffer = StringBuffer();
  int _indent = 0;

  /// Generate Dart code for an LCM file
  String generate(LcmFile file) {
    _buffer.clear();
    _indent = 0;

    // Register all structs for nested type fingerprint lookup
    _fingerprinter.registerStructs(file);

    // Generate each struct
    for (int i = 0; i < file.structs.length; i++) {
      if (i > 0) _writeln();
      _generateStruct(file.structs[i]);
    }

    return _buffer.toString();
  }

  /// Register additional structs for fingerprint calculation (e.g., from other files)
  void registerStructs(LcmFile file) {
    _fingerprinter.registerStructs(file);
  }

  void _generateStruct(StructDecl struct) {
    final className = _typeMapper.toPascalCase(struct.name);
    final fingerprint = _fingerprinter.computeFingerprint(struct);

    // File header
    _writeln('// LCM type definitions');
    _writeln('// This file automatically generated by lcm-dart.');
    _writeln('// DO NOT MODIFY BY HAND!!!!');
    _writeln();
    _writeln("import 'dart:convert';");
    _writeln("import 'dart:typed_data';");
    _writeln("import 'package:raccoon_transport/raccoon_transport.dart';");

    // Import nested (non-primitive) types
    final importedTypes = <String>{};
    for (final member in struct.members) {
      if (!member.type.isPrimitive && member.type.fullName != struct.fullName) {
        if (importedTypes.add(member.type.fullName)) {
          final importPath = _computeImportPath(struct, member.type);
          _writeln("import '$importPath';");
        }
      }
    }

    _writeln();

    // Doc comment
    if (struct.docComment != null) {
      for (final line in struct.docComment!.split('\n')) {
        _writeln('/// $line');
      }
    }

    // Class declaration
    _writeln('class $className implements LcmMessage {');
    _indent++;

    // Fingerprint constant - use BigInt for proper unsigned hex formatting
    final fpHex = BigInt.from(fingerprint).toUnsigned(64).toRadixString(16).padLeft(16, '0');
    _writeln('static const int LCM_FINGERPRINT = 0x$fpHex;');
    _writeln();

    // Constants
    if (struct.constants.isNotEmpty) {
      for (final constant in struct.constants) {
        final dartType = _typeMapper.mapType(constant.type);
        _writeln('static const $dartType ${constant.name} = ${constant.valueString};');
      }
      _writeln();
    }

    // Fields
    for (final member in struct.members) {
      final dartType = _getDartType(member);
      _writeln('$dartType ${member.name};');
    }
    _writeln();

    // Constructor
    _writeln('$className({');
    _indent++;
    for (final member in struct.members) {
      _writeln('required this.${member.name},');
    }
    _indent--;
    _writeln('});');
    _writeln();

    // Fingerprint getter
    _writeln('@override');
    _writeln('int get lcmFingerprint => LCM_FINGERPRINT;');
    _writeln();

    // Encode method
    _generateEncodeMethod(struct);
    _writeln();

    // Decode method
    _generateDecodeMethod(struct, className);

    _indent--;
    _writeln('}');
  }

  void _generateEncodeMethod(StructDecl struct) {
    // encode() - with fingerprint header, for top-level messages
    _writeln('@override');
    _writeln('void encode(LcmBuffer buf) {');
    _indent++;
    _writeln('buf.putInt64(LCM_FINGERPRINT);');
    _writeln('encodeBody(buf);');
    _indent--;
    _writeln('}');
    _writeln();

    // encodeBody() - fields only, used by nested types
    _writeln('@override');
    _writeln('void encodeBody(LcmBuffer buf) {');
    _indent++;

    for (final member in struct.members) {
      if (member.dimensions.isEmpty) {
        // Scalar
        _generateEncodeScalar(member.type.fullName, member.name);
      } else {
        // Array
        _generateEncodeArray(member);
      }
    }

    _indent--;
    _writeln('}');
  }

  void _generateEncodeScalar(String lcmType, String accessor) {
    if (lcmType == 'string') {
      _writeln('{');
      _indent++;
      _writeln('final bytes = utf8.encode($accessor);');
      _writeln('buf.putUint32(bytes.length + 1);');
      _writeln('buf.putUint8List(bytes);');
      _writeln('buf.putUint8(0);');
      _indent--;
      _writeln('}');
    } else if (lcmType == 'boolean') {
      _writeln('buf.putUint8($accessor ? 1 : 0);');
    } else if (_typeMapper.isNumericPrimitive(lcmType)) {
      final method = _typeMapper.getEncodeMethod(lcmType);
      _writeln('buf.$method($accessor);');
    } else {
      // Custom type - encode fields only (no fingerprint)
      _writeln('$accessor.encodeBody(buf);');
    }
  }

  void _generateEncodeArray(MemberDecl member) {
    final depth = member.dimensions.length;

    // Generate nested loops
    for (int d = 0; d < depth; d++) {
      final dim = member.dimensions[d];
      final indexVar = 'i$d';
      String sizeExpr;

      if (dim.isConstant) {
        sizeExpr = dim.size;
      } else {
        sizeExpr = dim.size; // Variable reference
      }

      _writeln('for (var $indexVar = 0; $indexVar < $sizeExpr; $indexVar++) {');
      _indent++;
    }

    // Generate accessor with all indices
    final accessor = StringBuffer(member.name);
    for (int d = 0; d < depth; d++) {
      accessor.write('[i$d]');
    }

    _generateEncodeScalar(member.type.fullName, accessor.toString());

    // Close loops
    for (int d = 0; d < depth; d++) {
      _indent--;
      _writeln('}');
    }
  }

  void _generateDecodeMethod(StructDecl struct, String className) {
    // decode() - with fingerprint check, for top-level messages
    _writeln('static $className decode(LcmBuffer buf) {');
    _indent++;
    _writeln('final fingerprint = buf.getInt64();');
    _writeln('if (fingerprint != LCM_FINGERPRINT) {');
    _indent++;
    _writeln("throw Exception('Invalid fingerprint: expected 0x\${BigInt.from(LCM_FINGERPRINT).toUnsigned(64).toRadixString(16).padLeft(16, '0')}, received 0x\${BigInt.from(fingerprint).toUnsigned(64).toRadixString(16).padLeft(16, '0')}');");
    _indent--;
    _writeln('}');
    _writeln('return decodeBody(buf);');
    _indent--;
    _writeln('}');
    _writeln();

    // decodeBody() - fields only, used by nested types
    _writeln('static $className decodeBody(LcmBuffer buf) {');
    _indent++;

    // Decode each field
    for (final member in struct.members) {
      if (member.dimensions.isEmpty) {
        // Scalar
        _generateDecodeScalar(member.type.fullName, member.name);
      } else {
        // Array
        _generateDecodeArray(member, struct);
      }
    }
    _writeln();

    // Return constructed object
    _writeln('return $className(');
    _indent++;
    for (final member in struct.members) {
      _writeln('${member.name}: ${member.name},');
    }
    _indent--;
    _writeln(');');

    _indent--;
    _writeln('}');
  }

  void _generateDecodeScalar(String lcmType, String varName) {
    if (lcmType == 'string') {
      _writeln('final $varName = () {');
      _indent++;
      _writeln('final len = buf.getUint32();');
      _writeln('final bytes = buf.getUint8List(len - 1);');
      _writeln('buf.getUint8(); // null terminator');
      _writeln('return utf8.decode(bytes);');
      _indent--;
      _writeln('}();');
    } else if (lcmType == 'boolean') {
      _writeln('final $varName = buf.getUint8() != 0;');
    } else if (_typeMapper.isNumericPrimitive(lcmType)) {
      final method = _typeMapper.getDecodeMethod(lcmType);
      _writeln('final $varName = buf.$method();');
    } else {
      // Custom type - decode fields only (no fingerprint)
      final typeName = _typeMapper.toPascalCase(_shortName(lcmType));
      _writeln('final $varName = $typeName.decodeBody(buf);');
    }
  }

  void _generateDecodeArray(MemberDecl member, StructDecl struct) {
    final depth = member.dimensions.length;

    // Initialize the array - use element type (starting from dim 1, not 0)
    _writeln('final ${member.name} = <${_getNestedListType(member, 1)}>[];');

    // Generate nested loops
    for (int d = 0; d < depth; d++) {
      final dim = member.dimensions[d];
      final indexVar = 'i$d';
      String sizeExpr;

      if (dim.isConstant) {
        sizeExpr = dim.size;
      } else {
        sizeExpr = dim.size; // Variable reference
      }

      _writeln('for (var $indexVar = 0; $indexVar < $sizeExpr; $indexVar++) {');
      _indent++;

      // Add inner list if not at deepest level
      if (d < depth - 1) {
        final accessor = _buildAccessor(member.name, d);
        // Use element type of dimension d+1 (which is _getNestedListType starting from d+2)
        _writeln('$accessor.add(<${_getNestedListType(member, d + 2)}>[]);');
      }
    }

    // Decode the element
    final tempVar = '${member.name}Element';
    _generateDecodeScalar(member.type.fullName, tempVar);

    // Add to array
    final accessor = _buildAccessor(member.name, depth - 1);
    _writeln('$accessor.add($tempVar);');

    // Close loops
    for (int d = 0; d < depth; d++) {
      _indent--;
      _writeln('}');
    }
  }

  String _buildAccessor(String name, int depth) {
    final buffer = StringBuffer(name);
    for (int d = 0; d < depth; d++) {
      buffer.write('[i$d]');
    }
    return buffer.toString();
  }

  String _getNestedListType(MemberDecl member, int startDim) {
    if (startDim >= member.dimensions.length) {
      return _typeMapper.mapType(member.type.fullName);
    }

    final inner = _getNestedListType(member, startDim + 1);
    return 'List<$inner>';
  }

  String _getDartType(MemberDecl member) {
    if (member.dimensions.isEmpty) {
      return _typeMapper.mapType(member.type.fullName);
    }

    // Build nested list type
    String type = _typeMapper.mapType(member.type.fullName);
    for (int i = 0; i < member.dimensions.length; i++) {
      type = 'List<$type>';
    }
    return type;
  }

  String _computeImportPath(StructDecl currentStruct, TypeRef referencedType) {
    final currentPkg = currentStruct.package;
    final refPkg = referencedType.package;

    if (currentPkg == refPkg) {
      // Same package (or both null) - simple relative import
      return '${referencedType.shortName}.g.dart';
    }

    // Different packages - compute relative path
    final currentParts = currentPkg?.split('.') ?? [];
    final refParts = refPkg?.split('.') ?? [];

    final buffer = StringBuffer();
    // Go up from current package directory
    for (var i = 0; i < currentParts.length; i++) {
      buffer.write('../');
    }
    // Go down into referenced package directory
    for (final part in refParts) {
      buffer.write('$part/');
    }
    buffer.write('${referencedType.shortName}.g.dart');
    return buffer.toString();
  }

  String _shortName(String fullName) {
    final dotIndex = fullName.lastIndexOf('.');
    return dotIndex >= 0 ? fullName.substring(dotIndex + 1) : fullName;
  }

  void _writeln([String text = '']) {
    if (text.isNotEmpty) {
      _buffer.write('  ' * _indent);
      _buffer.writeln(text);
    } else {
      _buffer.writeln();
    }
  }
}
