// LCM type definitions
// This file automatically generated by lcm-dart.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:raccoon_transport/raccoon_transport.dart';
import 'cam_blob_t.g.dart';

class CamFrameT implements LcmMessage {
  static const int LCM_FINGERPRINT = 0x4879ec21b38f492b;

  int timestamp;
  int frame_width;
  int frame_height;
  int frame_size;
  List<int> frame_data;
  int num_detections;
  List<CamBlobT> detections;

  CamFrameT({
    required this.timestamp,
    required this.frame_width,
    required this.frame_height,
    required this.frame_size,
    required this.frame_data,
    required this.num_detections,
    required this.detections,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    encodeBody(buf);
  }

  @override
  void encodeBody(LcmBuffer buf) {
    buf.putInt64(timestamp);
    buf.putInt32(frame_width);
    buf.putInt32(frame_height);
    buf.putInt32(frame_size);
    for (var i0 = 0; i0 < frame_size; i0++) {
      buf.putUint8(frame_data[i0]);
    }
    buf.putInt32(num_detections);
    for (var i0 = 0; i0 < num_detections; i0++) {
      detections[i0].encodeBody(buf);
    }
  }

  static CamFrameT decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint: expected 0x${BigInt.from(LCM_FINGERPRINT).toUnsigned(64).toRadixString(16).padLeft(16, '0')}, received 0x${BigInt.from(fingerprint).toUnsigned(64).toRadixString(16).padLeft(16, '0')}');
    }
    return decodeBody(buf);
  }

  static CamFrameT decodeBody(LcmBuffer buf) {
    final timestamp = buf.getInt64();
    final frame_width = buf.getInt32();
    final frame_height = buf.getInt32();
    final frame_size = buf.getInt32();
    final frame_data = <int>[];
    for (var i0 = 0; i0 < frame_size; i0++) {
      final frame_dataElement = buf.getUint8();
      frame_data.add(frame_dataElement);
    }
    final num_detections = buf.getInt32();
    final detections = <CamBlobT>[];
    for (var i0 = 0; i0 < num_detections; i0++) {
      final detectionsElement = CamBlobT.decodeBody(buf);
      detections.add(detectionsElement);
    }

    return CamFrameT(
      timestamp: timestamp,
      frame_width: frame_width,
      frame_height: frame_height,
      frame_size: frame_size,
      frame_data: frame_data,
      num_detections: num_detections,
      detections: detections,
    );
  }
}
