// LCM type definitions
// This file automatically generated by lcm-dart.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:raccoon_transport/raccoon_transport.dart';

class CamConfigT implements LcmMessage {
  static const int LCM_FINGERPRINT = 0xe0e0653bd7b7d18a;

  int timestamp;
  String config;

  CamConfigT({
    required this.timestamp,
    required this.config,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    encodeBody(buf);
  }

  @override
  void encodeBody(LcmBuffer buf) {
    buf.putInt64(timestamp);
    {
      final bytes = utf8.encode(config);
      buf.putUint32(bytes.length + 1);
      buf.putUint8List(bytes);
      buf.putUint8(0);
    }
  }

  static CamConfigT decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint: expected 0x${BigInt.from(LCM_FINGERPRINT).toUnsigned(64).toRadixString(16).padLeft(16, '0')}, received 0x${BigInt.from(fingerprint).toUnsigned(64).toRadixString(16).padLeft(16, '0')}');
    }
    return decodeBody(buf);
  }

  static CamConfigT decodeBody(LcmBuffer buf) {
    final timestamp = buf.getInt64();
    final config = () {
      final len = buf.getUint32();
      final bytes = buf.getUint8List(len - 1);
      buf.getUint8(); // null terminator
      return utf8.decode(bytes);
    }();

    return CamConfigT(
      timestamp: timestamp,
      config: config,
    );
  }
}
