// LCM type definitions
// This file automatically generated by lcm-dart.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:raccoon_transport/raccoon_transport.dart';

class CamStreamCtlT implements LcmMessage {
  static const int LCM_FINGERPRINT = 0xf5a8b80ac4119739;

  int timestamp;
  int enabled;

  CamStreamCtlT({
    required this.timestamp,
    required this.enabled,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    encodeBody(buf);
  }

  @override
  void encodeBody(LcmBuffer buf) {
    buf.putInt64(timestamp);
    buf.putInt8(enabled);
  }

  static CamStreamCtlT decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint: expected 0x${BigInt.from(LCM_FINGERPRINT).toUnsigned(64).toRadixString(16).padLeft(16, '0')}, received 0x${BigInt.from(fingerprint).toUnsigned(64).toRadixString(16).padLeft(16, '0')}');
    }
    return decodeBody(buf);
  }

  static CamStreamCtlT decodeBody(LcmBuffer buf) {
    final timestamp = buf.getInt64();
    final enabled = buf.getInt8();

    return CamStreamCtlT(
      timestamp: timestamp,
      enabled: enabled,
    );
  }
}
