// LCM type definitions
// This file automatically generated by lcm-dart.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:raccoon_transport/raccoon_transport.dart';

class OrientationMatrixT implements LcmMessage {
  static const int LCM_FINGERPRINT = 0x9a9992cda9c4bb6f;

  int timestamp;
  List<int> m;

  OrientationMatrixT({
    required this.timestamp,
    required this.m,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    encodeBody(buf);
  }

  @override
  void encodeBody(LcmBuffer buf) {
    buf.putInt64(timestamp);
    for (var i0 = 0; i0 < 9; i0++) {
      buf.putInt8(m[i0]);
    }
  }

  static OrientationMatrixT decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint: expected 0x${BigInt.from(LCM_FINGERPRINT).toUnsigned(64).toRadixString(16).padLeft(16, '0')}, received 0x${BigInt.from(fingerprint).toUnsigned(64).toRadixString(16).padLeft(16, '0')}');
    }
    return decodeBody(buf);
  }

  static OrientationMatrixT decodeBody(LcmBuffer buf) {
    final timestamp = buf.getInt64();
    final m = <int>[];
    for (var i0 = 0; i0 < 9; i0++) {
      final mElement = buf.getInt8();
      m.add(mElement);
    }

    return OrientationMatrixT(
      timestamp: timestamp,
      m: m,
    );
  }
}
