// LCM type definitions
// This file automatically generated by lcm-dart.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:raccoon_transport/raccoon_transport.dart';

class ScalarI32T implements LcmMessage {
  static const int LCM_FINGERPRINT = 0xa6d2b1f24dd5a609;

  int timestamp;
  int value;

  ScalarI32T({
    required this.timestamp,
    required this.value,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    encodeBody(buf);
  }

  @override
  void encodeBody(LcmBuffer buf) {
    buf.putInt64(timestamp);
    buf.putInt32(value);
  }

  static ScalarI32T decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint: expected 0x${BigInt.from(LCM_FINGERPRINT).toUnsigned(64).toRadixString(16).padLeft(16, '0')}, received 0x${BigInt.from(fingerprint).toUnsigned(64).toRadixString(16).padLeft(16, '0')}');
    }
    return decodeBody(buf);
  }

  static ScalarI32T decodeBody(LcmBuffer buf) {
    final timestamp = buf.getInt64();
    final value = buf.getInt32();

    return ScalarI32T(
      timestamp: timestamp,
      value: value,
    );
  }
}
