// Originally generated by lcm-dart, then hand-adapted to match
// raccoon-lib's hand-rolled `ScreenRender` raw byte encoding
// (see raccoon-lib/modules/libstp-screen/python/raccoon/ui/messages.py
// and ui_messages.hpp). No more LCM fingerprint, no more null-terminator
// on strings.
//
// Wire format (big-endian, tightly packed):
//   int64  timestamp
//   uint32 screen_name length (bytes)
//   utf8   screen_name
//   uint32 entries length (bytes)
//   utf8   entries

import 'dart:convert';
import 'dart:typed_data';
import 'package:raccoon_transport/raccoon_transport.dart';

class ScreenRenderT implements LcmMessage {
  int timestamp;
  String screen_name;
  String entries;

  ScreenRenderT({
    required this.timestamp,
    required this.screen_name,
    required this.entries,
  });

  @override
  int get lcmFingerprint => 0;

  @override
  void encode(LcmBuffer buf) {
    encodeBody(buf);
  }

  @override
  void encodeBody(LcmBuffer buf) {
    buf.putInt64(timestamp);
    {
      final bytes = utf8.encode(screen_name);
      buf.putUint32(bytes.length);
      buf.putUint8List(bytes);
    }
    {
      final bytes = utf8.encode(entries);
      buf.putUint32(bytes.length);
      buf.putUint8List(bytes);
    }
  }

  static ScreenRenderT decode(LcmBuffer buf) {
    return decodeBody(buf);
  }

  static ScreenRenderT decodeBody(LcmBuffer buf) {
    final timestamp = buf.getInt64();
    final screenName = () {
      final len = buf.getUint32();
      final bytes = buf.getUint8List(len);
      return utf8.decode(bytes);
    }();
    final entries = () {
      final len = buf.getUint32();
      final bytes = buf.getUint8List(len);
      return utf8.decode(bytes);
    }();

    return ScreenRenderT(
      timestamp: timestamp,
      screen_name: screenName,
      entries: entries,
    );
  }
}
