// LCM type definitions
// This file automatically generated by lcm-dart.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:raccoon_transport/raccoon_transport.dart';

class Vector3fT implements LcmMessage {
  static const int LCM_FINGERPRINT = 0x7276f63b94f9c752;

  int timestamp;
  double x;
  double y;
  double z;

  Vector3fT({
    required this.timestamp,
    required this.x,
    required this.y,
    required this.z,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    encodeBody(buf);
  }

  @override
  void encodeBody(LcmBuffer buf) {
    buf.putInt64(timestamp);
    buf.putFloat32(x);
    buf.putFloat32(y);
    buf.putFloat32(z);
  }

  static Vector3fT decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint: expected 0x${BigInt.from(LCM_FINGERPRINT).toUnsigned(64).toRadixString(16).padLeft(16, '0')}, received 0x${BigInt.from(fingerprint).toUnsigned(64).toRadixString(16).padLeft(16, '0')}');
    }
    return decodeBody(buf);
  }

  static Vector3fT decodeBody(LcmBuffer buf) {
    final timestamp = buf.getInt64();
    final x = buf.getFloat32();
    final y = buf.getFloat32();
    final z = buf.getFloat32();

    return Vector3fT(
      timestamp: timestamp,
      x: x,
      y: y,
      z: z,
    );
  }
}
