// LCM type definitions
// This file automatically generated by lcm-dart.
// DO NOT MODIFY BY HAND!!!!

import 'dart:convert';
import 'dart:typed_data';
import 'package:raccoon_transport/raccoon_transport.dart';

class YoloBoxT implements LcmMessage {
  static const int LCM_FINGERPRINT = 0x1e787544bf9ac9f0;

  int timestamp;
  double x;
  double y;
  double width;
  double height;
  String label;
  double confidence;

  YoloBoxT({
    required this.timestamp,
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    required this.label,
    required this.confidence,
  });

  @override
  int get lcmFingerprint => LCM_FINGERPRINT;

  @override
  void encode(LcmBuffer buf) {
    buf.putInt64(LCM_FINGERPRINT);
    encodeBody(buf);
  }

  @override
  void encodeBody(LcmBuffer buf) {
    buf.putInt64(timestamp);
    buf.putFloat32(x);
    buf.putFloat32(y);
    buf.putFloat32(width);
    buf.putFloat32(height);
    {
      final bytes = utf8.encode(label);
      buf.putUint32(bytes.length + 1);
      buf.putUint8List(bytes);
      buf.putUint8(0);
    }
    buf.putFloat32(confidence);
  }

  static YoloBoxT decode(LcmBuffer buf) {
    final fingerprint = buf.getInt64();
    if (fingerprint != LCM_FINGERPRINT) {
      throw Exception('Invalid fingerprint: expected 0x${BigInt.from(LCM_FINGERPRINT).toUnsigned(64).toRadixString(16).padLeft(16, '0')}, received 0x${BigInt.from(fingerprint).toUnsigned(64).toRadixString(16).padLeft(16, '0')}');
    }
    return decodeBody(buf);
  }

  static YoloBoxT decodeBody(LcmBuffer buf) {
    final timestamp = buf.getInt64();
    final x = buf.getFloat32();
    final y = buf.getFloat32();
    final width = buf.getFloat32();
    final height = buf.getFloat32();
    final label = () {
      final len = buf.getUint32();
      final bytes = buf.getUint8List(len - 1);
      buf.getUint8(); // null terminator
      return utf8.decode(bytes);
    }();
    final confidence = buf.getFloat32();

    return YoloBoxT(
      timestamp: timestamp,
      x: x,
      y: y,
      width: width,
      height: height,
      label: label,
      confidence: confidence,
    );
  }
}
