"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ack_t(object):

    __slots__ = ["timestamp", "publisher_id", "seq_num", "subscriber_id"]

    __typenames__ = ["int64_t", "string", "int64_t", "string"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.publisher_id = ""
        """ LCM Type: string """
        self.seq_num = 0
        """ LCM Type: int64_t """
        self.subscriber_id = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(ack_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __publisher_id_encoded = self.publisher_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__publisher_id_encoded)+1))
        buf.write(__publisher_id_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">q", self.seq_num))
        __subscriber_id_encoded = self.subscriber_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__subscriber_id_encoded)+1))
        buf.write(__subscriber_id_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ack_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ack_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ack_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __publisher_id_len = struct.unpack('>I', buf.read(4))[0]
        self.publisher_id = buf.read(__publisher_id_len)[:-1].decode('utf-8', 'replace')
        self.seq_num = struct.unpack(">q", buf.read(8))[0]
        __subscriber_id_len = struct.unpack('>I', buf.read(4))[0]
        self.subscriber_id = buf.read(__subscriber_id_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ack_t in parents: return 0
        tmphash = (0xac3540153e27ca42) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ack_t._packed_fingerprint is None:
            ack_t._packed_fingerprint = struct.pack(">Q", ack_t._get_hash_recursive([]))
        return ack_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ack_t._get_packed_fingerprint())[0]

