"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class cam_config_t(object):

    __slots__ = ["timestamp", "config"]

    __typenames__ = ["int64_t", "string"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.config = ""
        """ LCM Type: string """

    def encode(self):
        buf = BytesIO()
        buf.write(cam_config_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __config_encoded = self.config.encode('utf-8')
        buf.write(struct.pack('>I', len(__config_encoded)+1))
        buf.write(__config_encoded)
        buf.write(b"\0")

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cam_config_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cam_config_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = cam_config_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __config_len = struct.unpack('>I', buf.read(4))[0]
        self.config = buf.read(__config_len)[:-1].decode('utf-8', 'replace')
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if cam_config_t in parents: return 0
        tmphash = (0x7070329debdbe8c5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if cam_config_t._packed_fingerprint is None:
            cam_config_t._packed_fingerprint = struct.pack(">Q", cam_config_t._get_hash_recursive([]))
        return cam_config_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cam_config_t._get_packed_fingerprint())[0]

