"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from raccoon_transport.types import raccoon

class cam_detections_t(object):

    __slots__ = ["timestamp", "frame_width", "frame_height", "num_detections", "detections"]

    __typenames__ = ["int64_t", "int32_t", "int32_t", "int32_t", "raccoon.cam_blob_t"]

    __dimensions__ = [None, None, None, None, ["num_detections"]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.frame_width = 0
        """ LCM Type: int32_t """
        self.frame_height = 0
        """ LCM Type: int32_t """
        self.num_detections = 0
        """ LCM Type: int32_t """
        self.detections = []
        """ LCM Type: raccoon.cam_blob_t[num_detections] """

    def encode(self):
        buf = BytesIO()
        buf.write(cam_detections_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiii", self.timestamp, self.frame_width, self.frame_height, self.num_detections))
        for i0 in range(self.num_detections):
            assert self.detections[i0]._get_packed_fingerprint() == raccoon.cam_blob_t._get_packed_fingerprint()
            self.detections[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cam_detections_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cam_detections_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = cam_detections_t()
        self.timestamp, self.frame_width, self.frame_height, self.num_detections = struct.unpack(">qiii", buf.read(20))
        self.detections = []
        for i0 in range(self.num_detections):
            self.detections.append(raccoon.cam_blob_t._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if cam_detections_t in parents: return 0
        newparents = parents + [cam_detections_t]
        tmphash = (0xb729417a291dcfda+ raccoon.cam_blob_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if cam_detections_t._packed_fingerprint is None:
            cam_detections_t._packed_fingerprint = struct.pack(">Q", cam_detections_t._get_hash_recursive([]))
        return cam_detections_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cam_detections_t._get_packed_fingerprint())[0]

