"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class cam_blob_t(object):

    __slots__ = ["timestamp", "label", "x", "y", "width", "height", "area", "confidence"]

    __typenames__ = ["int64_t", "string", "float", "float", "float", "float", "int32_t", "float"]

    __dimensions__ = [None, None, None, None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.label = ""
        """ LCM Type: string """
        self.x = 0.0
        """
        color name, e.g. "orange"
        LCM Type: float
        """

        self.y = 0.0
        """
        center x, normalized 0.0-1.0
        LCM Type: float
        """

        self.width = 0.0
        """
        center y, normalized 0.0-1.0
        LCM Type: float
        """

        self.height = 0.0
        """
        bounding box width, normalized 0.0-1.0
        LCM Type: float
        """

        self.area = 0
        """
        bounding box height, normalized 0.0-1.0
        LCM Type: int32_t
        """

        self.confidence = 0.0
        """
        blob area in pixels
        LCM Type: float
        """


    def encode(self):
        buf = BytesIO()
        buf.write(cam_blob_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __label_encoded = self.label.encode('utf-8')
        buf.write(struct.pack('>I', len(__label_encoded)+1))
        buf.write(__label_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ffffif", self.x, self.y, self.width, self.height, self.area, self.confidence))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cam_blob_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cam_blob_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = cam_blob_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __label_len = struct.unpack('>I', buf.read(4))[0]
        self.label = buf.read(__label_len)[:-1].decode('utf-8', 'replace')
        self.x, self.y, self.width, self.height, self.area, self.confidence = struct.unpack(">ffffif", buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if cam_blob_t in parents: return 0
        tmphash = (0xe65edc7d366894df) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if cam_blob_t._packed_fingerprint is None:
            cam_blob_t._packed_fingerprint = struct.pack(">Q", cam_blob_t._get_hash_recursive([]))
        return cam_blob_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", cam_blob_t._get_packed_fingerprint())[0]

