"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class envelope_t(object):

    __slots__ = ["timestamp", "publisher_id", "seq_num", "channel", "payload_size", "payload"]

    __typenames__ = ["int64_t", "string", "int64_t", "string", "int32_t", "byte"]

    __dimensions__ = [None, None, None, None, None, ["payload_size"]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.publisher_id = ""
        """ LCM Type: string """
        self.seq_num = 0
        """ LCM Type: int64_t """
        self.channel = ""
        """ LCM Type: string """
        self.payload_size = 0
        """ LCM Type: int32_t """
        self.payload = b""
        """ LCM Type: byte[payload_size] """

    def encode(self):
        buf = BytesIO()
        buf.write(envelope_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __publisher_id_encoded = self.publisher_id.encode('utf-8')
        buf.write(struct.pack('>I', len(__publisher_id_encoded)+1))
        buf.write(__publisher_id_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">q", self.seq_num))
        __channel_encoded = self.channel.encode('utf-8')
        buf.write(struct.pack('>I', len(__channel_encoded)+1))
        buf.write(__channel_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.payload_size))
        buf.write(bytearray(self.payload[:self.payload_size]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != envelope_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return envelope_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = envelope_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __publisher_id_len = struct.unpack('>I', buf.read(4))[0]
        self.publisher_id = buf.read(__publisher_id_len)[:-1].decode('utf-8', 'replace')
        self.seq_num = struct.unpack(">q", buf.read(8))[0]
        __channel_len = struct.unpack('>I', buf.read(4))[0]
        self.channel = buf.read(__channel_len)[:-1].decode('utf-8', 'replace')
        self.payload_size = struct.unpack(">i", buf.read(4))[0]
        self.payload = buf.read(self.payload_size)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if envelope_t in parents: return 0
        tmphash = (0xe68bfc03c6cb3940) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if envelope_t._packed_fingerprint is None:
            envelope_t._packed_fingerprint = struct.pack(">Q", envelope_t._get_hash_recursive([]))
        return envelope_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", envelope_t._get_packed_fingerprint())[0]

