"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class orientation_matrix_t(object):

    __slots__ = ["timestamp", "m"]

    __typenames__ = ["int64_t", "int8_t"]

    __dimensions__ = [None, [9]]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.m = [ 0 for dim0 in range(9) ]
        """ LCM Type: int8_t[9] """

    def encode(self):
        buf = BytesIO()
        buf.write(orientation_matrix_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>9b', *self.m[:9]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != orientation_matrix_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return orientation_matrix_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = orientation_matrix_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.m = struct.unpack('>9b', buf.read(9))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if orientation_matrix_t in parents: return 0
        tmphash = (0xcd4cc966d4e25db7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if orientation_matrix_t._packed_fingerprint is None:
            orientation_matrix_t._packed_fingerprint = struct.pack(">Q", orientation_matrix_t._get_hash_recursive([]))
        return orientation_matrix_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", orientation_matrix_t._get_packed_fingerprint())[0]

