"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class yolo_box_t(object):

    __slots__ = ["timestamp", "x", "y", "width", "height", "label", "confidence"]

    __typenames__ = ["int64_t", "float", "float", "float", "float", "string", "float"]

    __dimensions__ = [None, None, None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.x = 0.0
        """ LCM Type: float """
        self.y = 0.0
        """
        x coordinate of the box center (0.0 to 1.0, percentage of frame width)
        LCM Type: float
        """

        self.width = 0.0
        """
        y coordinate of the box center (0.0 to 1.0, percentage of frame height)
        LCM Type: float
        """

        self.height = 0.0
        """
        width of the box (0.0 to 1.0, percentage of frame width)
        LCM Type: float
        """

        self.label = ""
        """
        height of the box (0.0 to 1.0, percentage of frame height)
        LCM Type: string
        """

        self.confidence = 0.0
        """
        class label of the detected object
        LCM Type: float
        """


    def encode(self):
        buf = BytesIO()
        buf.write(yolo_box_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qffff", self.timestamp, self.x, self.y, self.width, self.height))
        __label_encoded = self.label.encode('utf-8')
        buf.write(struct.pack('>I', len(__label_encoded)+1))
        buf.write(__label_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">f", self.confidence))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != yolo_box_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return yolo_box_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = yolo_box_t()
        self.timestamp, self.x, self.y, self.width, self.height = struct.unpack(">qffff", buf.read(24))
        __label_len = struct.unpack('>I', buf.read(4))[0]
        self.label = buf.read(__label_len)[:-1].decode('utf-8', 'replace')
        self.confidence = struct.unpack(">f", buf.read(4))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if yolo_box_t in parents: return 0
        tmphash = (0xf3c3aa25fcd64f8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if yolo_box_t._packed_fingerprint is None:
            yolo_box_t._packed_fingerprint = struct.pack(">Q", yolo_box_t._get_hash_recursive([]))
        return yolo_box_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", yolo_box_t._get_packed_fingerprint())[0]

